apiVersion: v1
kind: Service
metadata:
  name: dev-project-service
  labels:
    app: dev-project
spec:
  selector:
    app: dev-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080